apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-huy
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
