apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-huy
  namespace: {{ template "jenkins.namespace" . }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/jenkins-volume/
